[package]
name = "whatwg_streams"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.5.0"
async-lock = "3.4.0"
async-trait = "0.1.88"
futures = "0.3.31"
futures-core = "0.3.31"
futures-sink = "0.3.31"
futures-timer = "3.0.3"
futures-util = "0.3.31"
parking_lot = "0.12.4"
pin-project = "1.1.10"

[dev-dependencies]
#tokio = "1.44.2"
tokio = { version = "1.44.2", features = ['full'] }
localtest-macros = { path = "../localtest-macros" }
