[package]
name = "whatwg_streams"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
futures-core = "0.3.31"
futures-sink = "0.3.31"
futures-util = "0.3.31"

[dev-dependencies]
#tokio = "1.44.2"
tokio = { version = "1.44.2", features = ['full'] }
